### PR TITLE
E2e cleanup.

### PR DESCRIPTION
**Pull request by arhamchordia**
Changes are made to update e2e test suite to work in tandem with the latest release of interchaintest repo of v8.

Still a work in progress PR as code is all cleaned up but it needs to be tested.

### CODE REVIEW

**Review by ajansari95 — DISMISSED** [review]
lgtm

**Comment by ajansari95** [comment]
the changes here lools good what else we need here as its draft?

**Comment by arhamchordia** [comment]
We need a hub deployment to pull images from.

**Comment by ajansari95** [comment]
> We need a hub deployment to pull images from.

i assume a docker image is needed?
can be pulled from here - https://github.com/cosmos/gaia/pkgs/container/gaia

**Comment by arhamchordia** [comment]
And if we just stick to cleanup then it is all set to merge.

**Review by ajansari95 — APPROVED** [review]

**Pull request merged**
