### PR TITLE
Remove commented out contracts

### PR DESCRIPTION
**Pull request by lubkoll**

### CODE REVIEW

**Review by arhamchordia — COMMENTED** [review]
Again same question here that we should remove these or not. I don't think we should remove airdrop contract.

**Comment by LaurensKubat** [comment]
Imo all these can be removed. If we need them again we can just readd them later. for the airdrop contract, we'd probably reuse our merkle incentives contract and infra right now to do a merkle airdrop

**Review by LaurensKubat — DISMISSED** [review]
lgtm

**Review by ajansari95 — APPROVED** [review]
lgtm

**Pull request merged**
